DogFactsWeb/Models/DogFactsResponse.cs
using Newtonsoft.Json;

namespace DogFactsWeb.Models
{
    public class DogFactsResponse
    {
        [JsonProperty("facts")]
        public string[] Facts { get; set; }
    }
}

DogFactsWeb/Models/DogFactsVM.cs
using System.ComponentModel.DataAnnotations;

namespace DogFactsWeb.Models
{
    public class DogFactsVM
    {
        public string? Url { get; set; }
        
        [Required]
        public IFormFile File { get; set; }
    }
}

DogFactsWeb/Models/ErrorViewModel.cs
namespace DogFactsWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DogFactsWeb/Models/GenericResponseVM.cs
namespace DogFactsWeb.Models
{
    public class GenericResponseVM
    {
        public GenericResponseVM()
        {
            Errors = new List<string>();
        }

        public string Message { get; set; }

        public IList<string> Errors { get; set; }

        public bool Ok => Errors.Count == 0;

        public GenericResponseVM AddError(string errorMessage)
        {
            Errors.Add(errorMessage);

            return this;
        }

        public GenericResponseVM AddMessage(string message)
        {
            this.Message = message;

            return this;
        }
    }
}

DogFactsWeb/Controllers/DogFactsController.cs
using DogFactsWeb.Models;
using DogFactsWeb.Services.Contracts;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Net.Http.Headers;

namespace DogFactsWeb.Controllers
{
    public class DogFactsController : Controller
    {
        private readonly DogFactsContract _dogFactsContract;

        public DogFactsController(DogFactsContract dogFactsContract)
        {
            _dogFactsContract = dogFactsContract;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> DogsConsult(DogFactsVM dogFactsVM)
        {
            if (ModelState.IsValid)
            {
                var response = await _dogFactsContract.GetDogFacts(dogFactsVM);

                if (response.Ok)
                {
                    ViewBag.Message = response.Message;
                    return View(nameof(Index));
                }
                else
                {
                    ViewBag.ErrorMessage = response.Errors;
                    return View("Error");
                }
            }

            return View(nameof(Index), dogFactsVM);
        }
    }
}

DogFactsWeb/Controllers/HomeController.cs
using DogFactsWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DogFactsWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DogFactsWeb/Views/DogFacts/Index.cshtml
@model DogFactsVM

<h2>Dog Facts</h2>
<div class="position-fixed top-0 end-0">
    <div class="toast align-items-center" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex">
            <div class="toast-body bg-success">
                @ViewBag.Message;
            </div>
            <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
</div>

<form asp-action="DogsConsult" enctype="multipart/form-data">
    <div class="form-horizontal">
        <hr />
        <div asp-validation-summary="All" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="Url" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group">
            <label asp-for="File" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input type="file" required="required" asp-for="File" class="form-control" accept="application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" />
                <span asp-validation-for="File" class="text-danger"></span>
            </div>
        </div>
        <br />

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-success" />
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @if (!string.IsNullOrWhiteSpace(ViewBag.Message))
    {
        <script>$(".toast").show();</script>
    }
<script>

    $(".btn-close").click(function() {
        $(".toast").hide();
    });

</script>

}

DogFactsWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DogFactsWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DogFactsWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DogFactsWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DogFactsWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DogFacts" asp-action="Index">Dog Facts</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - DogFactsWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>